#!/bin/sh

WANIFACE=/tmp/waniface

[ "$INTERFACE" = "wan" ] && {
	[ "$ACTION" = ifup ] && {
		echo $DEVICE > $WANIFACE
		iptables -v -t nat -I POSTROUTING -o $DEVICE -j MASQUERADE
	}
	[ "$ACTION" = ifdown ] && {
		if [ -f $WANIFACE ]; then
			iptables -v -t nat -D POSTROUTING -o $(cat $WANIFACE) -j MASQUERADE
		fi
	}
};

