#!/bin/sh

WANIFACE=/tmp/waniface

[ "$INTERFACE" = "wan" ] && {
	[ "$ACTION" = ifup ] && {
		iptables -v -t nat -I POSTROUTING -o $DEVICE -j MASQUERADE
		echo $DEVICE > $WANIFACE
	}
	[ "$ACTION" = ifdown ] && [ -f $WANIFACE ] && {
		DEVICE=$(cat $WANIFACE)
		iptables -v -t nat -D POSTROUTING -o $DEVICE -j MASQUERADE
	}
};

