#!/bin/sh

WANIFACE=/tmp/waniface

[ "$INTERFACE" = "wan" ] && {
	[ "$ACTION" = ifup ] && {
		echo $DEVICE > $WANIFACE
		iptables -A INPUT -i $DEVICE -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --set --name BRUTE-SSH --rsource
		iptables -A INPUT -i $DEVICE -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 --name BRUTE-SSH --rsource -j DROP
        }
        [ "$ACTION" = ifdown ] && {
                if [ -f $WANIFACE ]; then
			waniface=$(cat $WANIFACE)
			iptables -D INPUT -i $waniface -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --set --name BRUTE-SSH --rsource
			iptables -D INPUT -i $waniface -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 --name BRUTE-SSH --rsource -j DROP
		fi
        }
};

