#!/bin/sh

WANIFACE=/tmp/waniface

[ "$INTERFACE" = "wan" ] && {
	[ "$ACTION" = ifup ] && {
		iptables -A INPUT -i $DEVICE -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --set --name BRUTE-SSH --rsource
		iptables -A INPUT -i $DEVICE -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 --name BRUTE-SSH --rsource -j DROP
		echo $DEVICE > $WANIFACE
        }
        [ "$ACTION" = ifdown ] && [ -f $WANIFACE ] && {
		DEVICE=$(cat $WANIFACE)
		iptables -D INPUT -i $DEVICE -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --set --name BRUTE-SSH --rsource
		iptables -D INPUT -i $DEVICE -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 --name BRUTE-SSH --rsource -j DROP
        }
};

