#!/bin/sh

[ "$INTERFACE" = "wan" ] && {
	[ "$ACTION" = ifup ] && {
		logger -t $(cat /proc/sys/kernel/hostname) hostname
	}
	[ "$ACTION" = ifdown ] && {
		logger -t $(cat /proc/sys/kernel/hostname) hostname
	}
}
