#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=45

start() {
	iptables -t nat -I POSTROUTING -o PTP_WANIFACE_PTP -j MASQUERADE
}

stop() {
	iptables -t nat -D POSTROUTING -o PTP_WANIFACE_PTP -j MASQUERADE
}
