#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=45

start() {
	iptables -t nat -I POSTROUTING -o PTP_WANIFACE_PTP -j MASQUERADE
	iptables -A INPUT -i PTP_WANIFACE_PTP -p tcp -m tcp --dport 22 -m state --state NEW -m recent --set --name BRUTE-SSH --rsource
	iptables -A INPUT -i PTP_WANIFACE_PTP -p tcp -m tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 --name BRUTE-SSH --rsource -j DROP
	iptables -I FORWARD -i br-pub -p tcp --syn -m multiport --dports 6881:6889 -m recent --set --name TORRENTS  -j DROP
	iptables -I FORWARD -i br-pub -m recent --name TORRENTS --update --seconds 300 -j DROP
	iptables -I FORWARD -i br-pub -m recent --name TORRENTS --update --reap --seconds 300 -j DROP
	# approves private net traffic
	iptables -t filter -I FORWARD -s PTP_PRIVNET_PTP/PTP_PRIVMASKLEN_PTP -j ACCEPT
	iptables -t filter -I FORWARD -d PTP_PRIVNET_PTP/PTP_PRIVMASKLEN_PTP -m state  --state RELATED,ESTABLISHED -j ACCEPT
}

stop() {
	iptables -t nat -D POSTROUTING -o PTP_WANIFACE_PTP -j MASQUERADE
}
