#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=11

start() {
	# set date to a time when the openvpn tunnel keys are valid
	# in case ntpclient fails ... will allow vpn tunnel to come up
	date -s "2014-02-01 00:00"
}

