#!/bin/sh /etc/rc.common
# Copyright (C) 2008  Alina Friedrichsen <x-alina@gmx.net>
# Special thanks to bittorf wireless ))
START=65

PIDFILE=/var/run/olsr6d.pid
LOCKFILE=/var/run/olsrd-ipv6.lock

start() {
	olsrd -f /etc/olsr6d.conf -pidfile $PIDFILE -nofork < /dev/null > /dev/null &
}

stop() {
	kill $(cat $PIDFILE)
	rm -f $PIDFILE
	rm -f $LOCKFILE
}
